disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ifau.github.io"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  copyright = "© { year } ifau.github.io"

  [params.author]
    name = "Evgeny Seliverstov"
    image = "img/photo_square_small.jpg"
